name: Build patched FiveM

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    env:
      CFX_PRODUCT_NAME: fivem
      CFX_DRY_RUN: "true"
      CFX_RETAIL_BUILD: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Build FiveM client
        shell: pwsh
        run: |
          .\code\tools\ci\build_client.ps1

      - name: Upload caches
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fivem-build-output
          path: |
            caches/**
            .build-cache/**
            code/bin/**
