name: Build patched FiveM

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: FiveM
    runs-on: windows-2022

    env:
      PROGRAM: five
      PLATFORM: windows

    steps:
      - name: Checkout
        shell: bash
        run: |
          ROOT="C:\b"
          ROOT_REPO="$ROOT/$PROGRAM"
          ROOT_DEP="$ROOT/dep"
          JOB_SLOTS=$(nproc --all)

          echo "ROOT_REPO=$ROOT_REPO" >> "$GITHUB_ENV"
          echo "ROOT_DEP=$ROOT_DEP" >> "$GITHUB_ENV"
          echo "JOB_SLOTS=$JOB_SLOTS" >> "$GITHUB_ENV"

          mkdir -p "$ROOT_REPO"
          cd "$ROOT_REPO"

          git init .
          git config core.symlinks true
          git remote add origin "${{ github.server_url }}/${{ github.repository }}.git"
          git fetch origin "${{ github.sha }}" --depth=1
          git checkout FETCH_HEAD

          git submodule update \
            --jobs="$JOB_SLOTS" \
            --init \
            --depth=1

      - name: Dependencies
        shell: bash
        run: |
          mkdir -p "$ROOT_DEP"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python compatibility
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools

      - name: Configure node-gyp Python
        shell: pwsh
        run: |
          $python = (Get-Command python).Source
          echo "PYTHON=$python" >> $env:GITHUB_ENV
          echo "npm_config_python=$python" >> $env:GITHUB_ENV

      - name: Install Windows SDK 10.0.22000
        shell: pwsh
        run: |
          choco install windows-sdk-11-version-22H2-all -y --no-progress

      - name: Compile
        shell: bash
        run: |
          cd "$ROOT_REPO"

          # unset platform to avoid collisions
          BUILD_SCRIPT=".github/workflows/ci/build_windows.sh"
          PLATFORM=

          chmod +x "$BUILD_SCRIPT"
          "$BUILD_SCRIPT" "$ROOT_DEP" "$JOB_SLOTS"
