name: Build patched FiveM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python requirements
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Enable Corepack
        shell: pwsh
        run: corepack enable

      - name: Get Chromium
        shell: pwsh
        run: ./fxd.ps1 get-chrome

      - name: Prebuild
        shell: cmd
        run: prebuild.cmd

      - name: Generate FiveM project
        shell: pwsh
        run: ./fxd.ps1 gen -game five

      - name: Build FiveM
        shell: pwsh
        run: ./fxd.ps1 build -game five

      - name: Upload FiveM build
        uses: actions/upload-artifact@v4
        with:
          name: patched-fivem
          path: |
            code/bin/five/**
